# Generated by Django 3.2.13 on 2023-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdorodrigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paisagens',
            name='clima',
            field=models.CharField(max_length=50),
        ),
    ]
