# Generated by Django 3.2.13 on 2023-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdorodrigo', '0002_alter_paisagens_clima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curiosidades',
            name='categoria',
            field=models.CharField(choices=[('A', 'AMIGOS'), ('D', 'DATE'), ('F', 'FAMILIA')], max_length=1),
        ),
        migrations.AlterField(
            model_name='curiosidades',
            name='frequencia',
            field=models.CharField(choices=[('N', 'Nunca'), ('A', 'As vezes'), ('S', 'Sempre')], max_length=1),
        ),
    ]
